name: Codespell

on: [ pull_request ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Codespell with annotations
        uses: codespell-project/actions-codespell@v2.0
        with:
          check_filenames: true
          ignore_words_file: .github/.codespellignore
          uri_ignore_words_list: '*'
